# Generated by Django 3.2.25 on 2024-06-12 00:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('propietario', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('fecha_registro', models.DateField(default=datetime.date.today)),
                ('sintomas', models.TextField()),
            ],
        ),
    ]
